// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfKcLH4sTnEq0Tl8smZimRt5M6XCsTC4',
    appId: '1:445714580950:web:f3e6d4447da5254fe6d077',
    messagingSenderId: '445714580950',
    projectId: 'culinaryplus-8d1e1',
    authDomain: 'culinaryplus-8d1e1.firebaseapp.com',
    storageBucket: 'culinaryplus-8d1e1.firebasestorage.app',
    measurementId: 'G-SRVMK3V6YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkz1xkxldjgI1rBKgWO2FZtZWPDr9wZ4',
    appId: '1:445714580950:android:5717739dcc2726dce6d077',
    messagingSenderId: '445714580950',
    projectId: 'culinaryplus-8d1e1',
    storageBucket: 'culinaryplus-8d1e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBqYBZOc0_61nnUejX4jM4cOuQQJ-jXis',
    appId: '1:445714580950:ios:aecc2b6ff31be265e6d077',
    messagingSenderId: '445714580950',
    projectId: 'culinaryplus-8d1e1',
    storageBucket: 'culinaryplus-8d1e1.firebasestorage.app',
    androidClientId: '445714580950-1j3umf7jvnbvkd0sjsp4kop854145o0p.apps.googleusercontent.com',
    iosClientId: '445714580950-q75t3o9fns77qh8ks89q8orrei6afu1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.culinary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBqYBZOc0_61nnUejX4jM4cOuQQJ-jXis',
    appId: '1:445714580950:ios:aecc2b6ff31be265e6d077',
    messagingSenderId: '445714580950',
    projectId: 'culinaryplus-8d1e1',
    storageBucket: 'culinaryplus-8d1e1.firebasestorage.app',
    androidClientId: '445714580950-1j3umf7jvnbvkd0sjsp4kop854145o0p.apps.googleusercontent.com',
    iosClientId: '445714580950-q75t3o9fns77qh8ks89q8orrei6afu1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.culinary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEfKcLH4sTnEq0Tl8smZimRt5M6XCsTC4',
    appId: '1:445714580950:web:efa2888199922357e6d077',
    messagingSenderId: '445714580950',
    projectId: 'culinaryplus-8d1e1',
    authDomain: 'culinaryplus-8d1e1.firebaseapp.com',
    storageBucket: 'culinaryplus-8d1e1.firebasestorage.app',
    measurementId: 'G-TDCW9ZCPDX',
  );
}
